# Generated by Django 4.0.3 on 2022-10-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_signup', '0006_stops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stops',
            old_name='latitude',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='longitude',
        ),
        migrations.AddField(
            model_name='stops',
            name='long_lat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
