# Generated by Django 4.0.3 on 2022-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_signup', '0007_rename_latitude_stops_type_remove_stops_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stops',
        ),
        migrations.AddField(
            model_name='advertisers',
            name='address',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='advertisers',
            name='long_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisers',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
