# Generated by Django 4.0.3 on 2022-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_signup', '0008_delete_stops_advertisers_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisers',
            old_name='long_lat',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='advertisers',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
