# Generated by Django 4.0.3 on 2022-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0007_remove_user_purchase_list_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_purchase_list',
            name='complaint',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='user_purchase_list',
            name='response',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
