# Generated by Django 4.0.3 on 2022-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0008_user_purchase_list_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_purchase_list',
            name='address',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
