# Generated by Django 4.0.3 on 2022-10-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0009_user_purchase_list_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_purchase_list',
            name='ad_price',
            field=models.FloatField(),
        ),
    ]
